name: beans_merchant_sdk
description: "Beans Merchant API Library"
homepage: https://github.com/Beans-BV/merchant_sdk_dart
documentation: https://github.com/Beans-BV/merchant_sdk_dart
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
